FROM eclipse-temurin:23-jre-alpine AS runtime

WORKDIR /app

# Copy the built JAR file
COPY ./build/libs/*.jar geohod.jar

EXPOSE 8080 5005

# Create non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar geohod.jar"]