version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: geohod-postgres
    env_file:
      - .env
    environment:
      - 'POSTGRES_DB=geohod'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - geohod
    restart: always

  backend:
    image: geohod-backend:latest
    container_name: geohod-backend
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - geohod
    restart: always

networks:
  geohod:
    external: true

volumes:
  postgres-data: