services:
  geohod-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: geohod-backend:dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./src:/app/src
      - ./build.gradle:/app/build.gradle
      - ./settings.gradle:/app/settings.gradle
      - ./gradle:/app/gradle
      - gradle-cache:/root/.gradle
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port

  postgres:
    volumes:
      - geohod_postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  geohod_postgres_data_dev:
  gradle-cache:
