server:
  port: 8080
spring:
  application:
    name: geohod-backend
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:54321/geohod}
    username: ${SPRING_DATASOURCE_USERNAME:geohod}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

geohod:
  telegram-bot:
    token: 7966864729:AAFJdUnBGR7qw_jVn-rWX3y1dp97S5HVPSc
