server:
  port: 8080
spring:
  application:
    name: geohod-backend
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

geohod:
  telegram-bot:
    token: ${GEOHOD_TELEGRAM_BOT_TOKEN}
    username: ${GEOHOD_TELEGRAM_BOT_USERNAME}
  linkTemplates:
    eventRegistrationLink: ${GEOHOD_CREATED_EVENT_LINK_TEMPLATE}
