logging:
  level:
    root: INFO
    me.geohod: DEBUG
    org.springframework.security: WARN
    org.springframework.web.cors: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

spring:
  datasource:
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
  mvc:
    cors:
      allowed-origins:
        - "https://localhost:3000"
        - "https://127.0.0.1:3000"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

geohod:
  processor:
    in-app:
      delay: 10000
    telegram:
      delay: 10000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true