logging:
  level:
    org.springframework.security: debug
    org.springframework.web.cors: debug

spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/geohod
    username: geohod
    password: secret

geohod:
  telegram-bot:
    token: ${GEOHOD_TELEGRAM_BOT_TOKEN:dev-token}
    username: ${GEOHOD_TELEGRAM_BOT_USERNAME:dev-bot}
  linkTemplates:
    eventRegistrationLink: ${GEOHOD_CREATED_EVENT_LINK_TEMPLATE:https://t.me/{botName}/{eventId}}
  processor:
    in-app:
      delay: 5000
    telegram:
      delay: 5000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
