name: Update Changelog

on:
  pull_request_target:
    branches: [ main ]
    types: [ closed ]

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelog Entry
        uses: metcalfc/changelog-generator@v4
        with:
          mytoken: ${{ secrets.GITHUB_TOKEN }}
          base-ref: ${{ github.base_ref }}
          head-ref: ${{ github.sha }}

      - name: Save to CHANGELOG
        run: echo "${{ steps.changelog.outputs.changelog }}" > CHANGELOG.md

      - name: Check for Changes
        run: |
          if [ -z "${{ steps.changelog.outputs.changelog }}" ]; then
          echo "No changelog changes detected."
          exit 0
          fi

      - name: Commit Changelog Changes (if any)
        uses: EndBug/add-and-commit@v2
        with:
          message: 'Update CHANGELOG.md for PR # ${{ github.event.number }}'