name: Deploy to Production (Podman)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman podman-compose

    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Build Podman image
      run: |
        podman build -f .github/Dockerfile -t geohod-backend:latest .

    - name: Save Podman image
      run: |
        podman save geohod-backend:latest | gzip > geohod-backend-latest.tar.gz

    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ vars.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "geohod-backend-latest.tar.gz,deployments/prod/"
        target: "~/geohod-backend/"

    - name: Deploy to production
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ vars.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ~/geohod-backend
          
          # Load Podman image
          podman load < geohod-backend-latest.tar.gz
          
          # Create .env.prod file
          cat > deployments/prod/.env.prod << EOF
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_BOT_USERNAME=${{ secrets.TELEGRAM_BOT_USERNAME }}
          CORS_ALLOWED_ORIGINS=${{ vars.CORS_ALLOWED_ORIGINS }}
          GEOHOD_CREATED_EVENT_LINK_TEMPLATE=${{ vars.GEOHOD_CREATED_EVENT_LINK_TEMPLATE }}
          GEOHOD_REVIEW_LINK_TEMPLATE=${{ vars.GEOHOD_REVIEW_LINK_TEMPLATE }}
          EOF
          
          # Make scripts executable
          chmod +x deployments/prod/deploy-prod.sh
          chmod +x deployments/prod/deploy-prod-podman.sh
          
          ./deployments/prod/deploy-prod.sh
          
          # Cleanup
          rm geohod-backend-latest.tar.gz