name: Build and Deploy

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew clean build --no-daemon -x test

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.github/Dockerfile
          tags: ${{ github.repository }}:${{ github.ref_name }}
          outputs: type=docker,dest=./image.tar

      - name: Transfer files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: |
            ./image.tar
            ./docker-compose.yml
          target: /tmp/geohod-backend/
          overwrite: true
          rm: true

      - name: Cleanup local files
        if: always()
        run: |
          rm ./image.tar
          ./gradlew clean

      - name: Deploy on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /tmp/geohod-backend
            docker load < image.tar
            docker compose down
            docker compose up -d